common: &common
  # this is to map attributes as described in http://aaf.edu.au/technical/aaf-core-attributes/
  # to their respective field in the database
  # uncomment them if need be
  user-mapping:
    cn: ""
    displayname: ""
    edupersontargetedid: ""
    edupersonscopedaffiliation: ""
    edupersonprincipalname: ""
    mail: email
    givenname: first_name
    surname: last_name

development:
  <<: *common
  hostname: https://hcsvlab.alveo.edu.au
  secret_token:
  aaf_rc_login_url:

qa:
  <<: *common
  hostname: https://alveo-qa.alveo.edu.au
  secret_token:
  aaf_rc_login_url:

qa2:
  <<: *common
  hostname: https://alveo-qa2.alveo.edu.au
  secret_token:
  aaf_rc_login_url:

nci:
  <<: *common
  hostname: https://app.alveo.edu.au
  secret_token:
  aaf_rc_login_url: https://rapid.aaf.edu.au/jwt/authnrequest/research/REPLACE_ME

staging:
  <<: *common
  hostname: https://staging.alveo.edu.au
  secret_token:
  aaf_rc_login_url:

staging2:
  <<: *common
  hostname: https://alveo-staging2.sol1.net
  secret_token:
  aaf_rc_login_url:

test:
  <<: *common
  hostname: https://hcsvlab.alveo.edu.au
  secret_token:
  aaf_rc_login_url:

production:
  <<: *common
  hostname: http://example.com/must-be-a-url
  secret_token: REPLACE_ME
  aaf_rc_login_url: https://rapid.aaf.edu.au/jwt/authnrequest/research/REPLACE_ME

trove:
  <<: *common
  hostname: http://example.com/must-be-a-url
  secret_token: REPLACE_ME
  aaf_rc_login_url: https://rapid.aaf.edu.au/jwt/authnrequest/research/REPLACE_ME
