labels:
  RDF_type: 'RDF Type'
  DCTERMS_creator: 'Creator'
  DCTERMS_rights: 'Rights'
  http_purl_org_cld_terms_isLocatedAt: 'Is Located At'
  DCTERMS_custodian: 'Custodian'
  DCTERMS_subject: 'Subject'
  DCTERMS_title: 'Title'
  DCTERMS_description: 'Description'
  DCTERMS_bibliographicCitation: 'Bibliographic Citation'
  DCTERMS_title: 'Title'
  DCTERMS_abstract: 'Abstract'
  DCTERMS_accessRights: 'Access Rights'
  DCTERMS_contributor: 'Contributor'
  DCTERMS_alternative: 'Alternative Title'
  DCTERMS_created: 'Created'
  DCTERMS_extent: 'Extent'
  DCTERMS_is_part_of: 'Is Part Of'
  DCTERMS_isReferencedBy: 'Is Referenced By'
  DCTERMS_itemFormat: 'Item Format'
  DCTERMS_itemType: 'Item Type'
  DCTERMS_language: 'Language'
  DCTERMS_licence: 'Licence'
  DCTERMS_sensitivitystatement: 'Sensitivity Statement'
  LoC_OWN: 'Owner'
  DCTERMS_temporal: 'Temporal Coverage'
  http_purl_org_cld_terms_dateItemsCreated: 'Date Items Created'
  OLAC_language_facet: 'Language'