defaults: &defaults
  password_reset_email_sender: karl.li@mq.edu.au
  account_request_user_status_email_sender: karl.li@mq.edu.au
  account_request_admin_notification_sender: karl.li@mq.edu.au
  default_data_owner: karl.li@mq.edu.au
  licence_access_request_notification_sender: karl.li@mq.edu.au
  licence_access_request_response_sender: karl.li@mq.edu.au
  download_max_files: 9999
  download_tmp_dir: /mnt/volume/hcsvlab_download
  # tmp file expired time - hours
  download_expired_time: 24


development:
  <<: *defaults
  download_tmp_dir: tmp/hcsvlab_download

test:
  <<: *defaults
  download_tmp_dir: tmp/hcsvlab_download

production:
  password_reset_email_sender: steve.cassidy@mq.edu.au
  account_request_user_status_email_sender: steve.cassidy@mq.edu.au
  account_request_admin_notification_sender: steve.cassidy@mq.edu.au
  default_data_owner: steve.cassidy@mq.edu.au
  licence_access_request_notification_sender: steve.cassidy@mq.edu.au
  licence_access_request_response_sender: steve.cassidy@mq.edu.au

qa:
  <<: *defaults

qa2:
  <<: *defaults

nci:
  <<: *defaults
  password_reset_email_sender: steve.cassidy@mq.edu.au
  account_request_user_status_email_sender: steve.cassidy@mq.edu.au
  account_request_admin_notification_sender: steve.cassidy@mq.edu.au
  default_data_owner: steve.cassidy@mq.edu.au
  licence_access_request_notification_sender: steve.cassidy@mq.edu.au
  licence_access_request_response_sender: steve.cassidy@mq.edu.au

staging:
  <<: *defaults
  password_reset_email_sender: karl.li@mq.edu.au
  account_request_user_status_email_sender: karl.li@mq.edu.au
  account_request_admin_notification_sender: karl.li@mq.edu.au
  default_data_owner: karl.li@mq.edu.au
  licence_access_request_notification_sender: karl.li@mq.edu.au
  licence_access_request_response_sender: karl.li@mq.edu.au

staging2:
  password_reset_email_sender: karl.li@mq.edu.au
  account_request_user_status_email_sender: karl.li@mq.edu.au
  account_request_admin_notification_sender: karl.li@mq.edu.au
  default_data_owner: karl.li@mq.edu.au
  licence_access_request_notification_sender: karl.li@mq.edu.au
  licence_access_request_response_sender: karl.li@mq.edu.au

trove:
  password_reset_email_sender: karl.li@mq.edu.au
  account_request_user_status_email_sender: karl.li@mq.edu.au
  account_request_admin_notification_sender: karl.li@mq.edu.au
  default_data_owner: karl.li@mq.edu.au
  licence_access_request_notification_sender: karl.li@mq.edu.au
  licence_access_request_response_sender: karl.li@mq.edu.au
