:rabbitmq: &rabbitmq_common
  :client_class: Bunny
  :error_queue: error
  :vhost: /alveo
  :exchange: 'alveo.workers'

# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
development:
  <<: *rabbitmq_common
test:
  <<: *rabbitmq_common
qa:
  <<: *rabbitmq_common
qa2:
  <<: *rabbitmq_common
  :host: alveo-qa-mq.alveo.edu.au
nci:
  <<: *rabbitmq_common
staging:
  <<: *rabbitmq_common
staging2:
  <<: *rabbitmq_common
  :host: alveo-qa-mq.alveo.edu.au
production:
  <<: *rabbitmq_common
  :host: alveo-qa-mq.alveo.edu.au
trove:
  <<: *rabbitmq_common
  :host: alveo-mq.alveo.edu.au

