common: &common
  host: deployment-tracker.alveo.edu.au

# development:
#   host: localhost
#   port: 3001

qa: &qa
  <<: *common

qa2: &qa2
  <<: *common

nci: &qa2
  host: localhost
  port: 3001

staging:
  <<: *common

staging2:
  <<: *common

production:
  <<: *common

trove:
  <<: *common